export const BUILDPROCESSOR_TOPIC_BASE = "freemelt/0/BuildProcess/0";
export const BUILDPROCESSOR_COMPONENTS_TOPIC = `${BUILDPROCESSOR_TOPIC_BASE}/BuildStatus/components`;
export const BUILDPROCESSOR_COMPONENTS_TOPIC_WILDCARD = `${BUILDPROCESSOR_COMPONENTS_TOPIC}/+`;
